import {
  createLatexThemeRules,
  type LatexSyntaxPalette,
} from "./latex-theme-rules";

const monokaiPalette = {
  foreground: "F8F8F2",
  control: "FF5C8A",
  command: "66D9EF",
  escaped: "FF5C8A",
  environment: "A6E22E",
  mathEnvironment: "66D9EF",
  className: "AE81FF",
  packageName: "66D9EF",
  section: "E6DB74",
  sectionContent: "E6DB74",
  formatting: "A6E22E",
  formattedText: "F8F8F2",
  reference: "FD971F",
  referenceContent: "FFB454",
  functionName: "66D9EF",
  userMacro: "FF5C8A",
  mathDelimiter: "E6DB74",
  mathFunction: "66D9EF",
  mathFallback: "AE81FF",
  mathEscaped: "FF5C8A",
  mathArithmetic: "FD971F",
  mathBinary: "A6E22E",
  mathLarge: "FD971F",
  mathRelation: "FF5C8A",
  mathRelationSymbol: "FF79A4",
  mathLogic: "AE81FF",
  mathArrow: "66D9EF",
  mathGreek: "AE81FF",
  mathSymbol: "E6DB74",
  mathAccent: "A6E22E",
  mathFont: "66D9EF",
  mathDelimiterCommand: "E6DB74",
  mathSpacing: "9B9B8B",
  mathText: "E6DB74",
  mathNumber: "C4F05A",
  mathVariable: "F8F8F2",
  mathSubscript: "FF5C8A",
  mathAlignment: "66D9EF",
  mathPrime: "FD971F",
  mathPunctuation: "B5B5A8",
  mathCurly: "E6DB74",
  mathBracket: "66D9EF",
  mathParenthesis: "A6E22E",
  comment: "9B9B8B",
  number: "C4F05A",
  curly: "E6DB74",
  bracket: "66D9EF",
  parenthesis: "A6E22E",
  operator: "FD971F",
  comma: "B5B5A8",
  optionBracket: "66D9EF",
  requiredBlock: "A6E22E",
  optionName: "FF5C8A",
  assignment: "A6E22E",
  optionValue: "E6DB74",
  optionNumber: "C4F05A",
  verbatim: "E6DB74",
} satisfies LatexSyntaxPalette;

export const monokaiTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: createLatexThemeRules(monokaiPalette),
  colors: {
    "editor.background": "#272822",
    "editor.foreground": "#F8F8F2",
    "editor.lineHighlightBackground": "#3E3D32",
    "editorCursor.foreground": "#F8F8F0",
    "editorWhitespace.foreground": "#595A52",
    "editorIndentGuide.background": "#55564F",
    "editorLineNumber.foreground": "#A0A097",
    "editorBracketMatch.background": "#49483E",
    "editorBracketMatch.border": "#B5B5A8",
    "editor.selectionBackground": "#49483E",
    "editorBracketHighlight.foreground1": "#E6DB74",
    "editorBracketHighlight.foreground2": "#66D9EF",
    "editorBracketHighlight.foreground3": "#A6E22E",
    "editorBracketHighlight.foreground4": "#AE81FF",
    "editorBracketHighlight.foreground5": "#FF5C8A",
    "editorBracketHighlight.foreground6": "#FD971F",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF3333",
  },
};
