import {
  createLatexThemeRules,
  type LatexSyntaxPalette,
} from "./latex-theme-rules";

const highContrastPalette = {
  foreground: "FFFFFF",
  control: "FFFF00",
  command: "00FFFF",
  escaped: "FF8CFF",
  environment: "7CFC00",
  mathEnvironment: "00FFFF",
  className: "FFFFFF",
  packageName: "87CEFA",
  section: "FFB000",
  sectionContent: "FFFF00",
  formatting: "7CFC00",
  formattedText: "FFFFFF",
  reference: "FF8CFF",
  referenceContent: "FFB6FF",
  functionName: "00FFFF",
  userMacro: "FFA07A",
  mathDelimiter: "FFFFFF",
  mathFunction: "00FFFF",
  mathFallback: "87CEFA",
  mathEscaped: "FF8CFF",
  mathArithmetic: "FFB000",
  mathBinary: "7CFC00",
  mathLarge: "FFFF00",
  mathRelation: "FF8CFF",
  mathRelationSymbol: "FFB6FF",
  mathLogic: "FFFF00",
  mathArrow: "87CEFA",
  mathGreek: "FFFF00",
  mathSymbol: "7CFC00",
  mathAccent: "00FFFF",
  mathFont: "87CEFA",
  mathDelimiterCommand: "FFFFFF",
  mathSpacing: "B8B8B8",
  mathText: "FFB000",
  mathNumber: "00FF7F",
  mathVariable: "FFFFFF",
  mathSubscript: "FFA500",
  mathAlignment: "00FFFF",
  mathPrime: "FFFF00",
  mathPunctuation: "B8B8B8",
  mathCurly: "FFFF00",
  mathBracket: "FF8CFF",
  mathParenthesis: "00FFFF",
  comment: "B8B8B8",
  number: "00FF7F",
  curly: "FFFF00",
  bracket: "FF8CFF",
  parenthesis: "00FFFF",
  operator: "7CFC00",
  comma: "B8B8B8",
  optionBracket: "FF8CFF",
  requiredBlock: "00FFFF",
  optionName: "FF8CFF",
  assignment: "7CFC00",
  optionValue: "FFFF00",
  optionNumber: "00FF7F",
  verbatim: "FFB000",
} satisfies LatexSyntaxPalette;

export const dataTexHCTheme = {
  base: "hc-black" as const,
  inherit: true,
  rules: createLatexThemeRules(highContrastPalette, { highContrast: true }),
  colors: {
    "editor.background": "#000000",
    "editor.foreground": "#FFFFFF",
    "editor.lineHighlightBackground": "#FFFFFF20",
    "editorCursor.foreground": "#FFFFFF",
    "editorWhitespace.foreground": "#9A9A9A",
    "editorIndentGuide.background": "#FFFFFF",
    "editorLineNumber.foreground": "#FFFFFF",
    "editorBracketMatch.background": "#FFFFFF30",
    "editorBracketMatch.border": "#FFFFFF",
    "editorBracketHighlight.foreground1": "#FFFF00",
    "editorBracketHighlight.foreground2": "#00FFFF",
    "editorBracketHighlight.foreground3": "#7CFC00",
    "editorBracketHighlight.foreground4": "#FF8CFF",
    "editorBracketHighlight.foreground5": "#FFB000",
    "editorBracketHighlight.foreground6": "#FFFFFF",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF4040",
  },
};
