import {
  createLatexThemeRules,
  type LatexSyntaxPalette,
} from "./latex-theme-rules";

const darkPalette = {
  foreground: "D4D4D4",
  control: "FF78C6",
  command: "79C0FF",
  escaped: "FF9AD5",
  environment: "63E6BE",
  mathEnvironment: "4DD4FF",
  className: "B8C0FF",
  packageName: "82D2FF",
  section: "FFD166",
  sectionContent: "F4C95D",
  formatting: "7EE787",
  formattedText: "D4D4D4",
  reference: "C9A7FF",
  referenceContent: "BBA0F4",
  functionName: "79C0FF",
  userMacro: "FF9F68",
  mathDelimiter: "FF8E72",
  mathFunction: "5EEAD4",
  mathFallback: "79C0FF",
  mathEscaped: "FF9AD5",
  mathArithmetic: "FFB86C",
  mathBinary: "7EE787",
  mathLarge: "FFBA6B",
  mathRelation: "FF7AB2",
  mathRelationSymbol: "FF8CBF",
  mathLogic: "DDA6FF",
  mathArrow: "79C0FF",
  mathGreek: "C4A7FF",
  mathSymbol: "F2D66D",
  mathAccent: "63E6BE",
  mathFont: "82D2FF",
  mathDelimiterCommand: "FF8E72",
  mathSpacing: "9AA6A0",
  mathText: "F4C95D",
  mathNumber: "A8E063",
  mathVariable: "E6EAF2",
  mathSubscript: "FF9AD5",
  mathAlignment: "4DD4FF",
  mathPrime: "FFD166",
  mathPunctuation: "B7C0CC",
  mathCurly: "FFD166",
  mathBracket: "79C0FF",
  mathParenthesis: "7EE787",
  comment: "9AA6A0",
  number: "A8E063",
  curly: "FFD166",
  bracket: "79C0FF",
  parenthesis: "7EE787",
  operator: "7EE787",
  comma: "B7C0CC",
  optionBracket: "79C0FF",
  requiredBlock: "7EE787",
  optionName: "FF78C6",
  assignment: "7EE787",
  optionValue: "F4C95D",
  optionNumber: "A8E063",
  verbatim: "F4C95D",
} satisfies LatexSyntaxPalette;

export const dataTexDarkTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: createLatexThemeRules(darkPalette),
  colors: {
    "editor.background": "#1a1b1e",
    "editor.foreground": "#D4D4D4",
    "editor.lineHighlightBackground": "#2a2a2a",
    "editorCursor.foreground": "#A6E22E",
    "editorWhitespace.foreground": "#3B3A32",
    "editorIndentGuide.background": "#404040",
    "editorLineNumber.foreground": "#858585",
    "editorBracketMatch.background": "#3B3B3B",
    "editorBracketMatch.border": "#888888",
    "editorBracketHighlight.foreground1": "#FFD166",
    "editorBracketHighlight.foreground2": "#79C0FF",
    "editorBracketHighlight.foreground3": "#7EE787",
    "editorBracketHighlight.foreground4": "#C4A7FF",
    "editorBracketHighlight.foreground5": "#FF7AB2",
    "editorBracketHighlight.foreground6": "#FFB86C",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF5C5C",
  },
};
