import {
  createLatexThemeRules,
  type LatexSyntaxPalette,
} from "./latex-theme-rules";

const nordPalette = {
  foreground: "ECEFF4",
  control: "D8A6D8",
  command: "88C0D0",
  escaped: "D68A74",
  environment: "A3BE8C",
  mathEnvironment: "8FBCBB",
  className: "81A1C1",
  packageName: "88C0D0",
  section: "EBCB8B",
  sectionContent: "EBCB8B",
  formatting: "A3BE8C",
  formattedText: "ECEFF4",
  reference: "BA94B3",
  referenceContent: "C9A7C7",
  functionName: "88C0D0",
  userMacro: "D68A74",
  mathDelimiter: "EBCB8B",
  mathFunction: "8FBCBB",
  mathFallback: "88C0D0",
  mathEscaped: "D68A74",
  mathArithmetic: "D68A74",
  mathBinary: "A3BE8C",
  mathLarge: "D68A74",
  mathRelation: "D8A6D8",
  mathRelationSymbol: "BA94B3",
  mathLogic: "CAA6D5",
  mathArrow: "88C0D0",
  mathGreek: "BA94B3",
  mathSymbol: "81A1C1",
  mathAccent: "A3BE8C",
  mathFont: "81A1C1",
  mathDelimiterCommand: "EBCB8B",
  mathSpacing: "919EB8",
  mathText: "EBCB8B",
  mathNumber: "EBCB8B",
  mathVariable: "ECEFF4",
  mathSubscript: "D8A6D8",
  mathAlignment: "88C0D0",
  mathPrime: "EBCB8B",
  mathPunctuation: "9AA7BD",
  mathCurly: "EBCB8B",
  mathBracket: "88C0D0",
  mathParenthesis: "A3BE8C",
  comment: "919EB8",
  number: "EBCB8B",
  curly: "EBCB8B",
  bracket: "88C0D0",
  parenthesis: "A3BE8C",
  operator: "D68A74",
  comma: "9AA7BD",
  optionBracket: "88C0D0",
  requiredBlock: "A3BE8C",
  optionName: "D8A6D8",
  assignment: "A3BE8C",
  optionValue: "EBCB8B",
  optionNumber: "EBCB8B",
  verbatim: "A3BE8C",
} satisfies LatexSyntaxPalette;

export const nordTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: createLatexThemeRules(nordPalette),
  colors: {
    "editor.background": "#2E3440",
    "editor.foreground": "#ECEFF4",
    "editor.lineHighlightBackground": "#3B4252",
    "editorCursor.foreground": "#D8DEE9",
    "editorWhitespace.foreground": "#596579",
    "editorIndentGuide.background": "#4C566A",
    "editorLineNumber.foreground": "#7F8CA3",
    "editorBracketMatch.background": "#434C5E",
    "editorBracketMatch.border": "#88C0D0",
    "editor.selectionBackground": "#434C5E",
    "editorBracketHighlight.foreground1": "#EBCB8B",
    "editorBracketHighlight.foreground2": "#88C0D0",
    "editorBracketHighlight.foreground3": "#A3BE8C",
    "editorBracketHighlight.foreground4": "#BA94B3",
    "editorBracketHighlight.foreground5": "#D68A74",
    "editorBracketHighlight.foreground6": "#8FBCBB",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF6B7A",
  },
};
